import "./globals.css";
import { Roboto } from "next/font/google";
import Navbar from "@/components/Navbar";
import Providers from "@/components/RtkProvider";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata = {
  title: "Redux-Crud",
  description: "Generated by Rofikul Islam Resan",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
